import type {
  Category,
  Product,
  Review,
  Order,
  User,
  DashboardStats,
  Banner,
} from "./types";

// ─── Banners ───────────────────────────────────────────────────────────────

export const initialBanners: Banner[] = [
  {
    id: "banner_1",
    image: "/images/hero-spices.png",
    isActive: true,
  },
  {
    id: "banner_2",
    image: "/images/banner1.png",
    isActive: true,
  },
  {
    id: "banner_3",
    image: "/images/banner2.png",
    isActive: true,
  },
];

// ─── Categories ──────────────────────────────────────────────────────────────

export const categories: Category[] = [
  {
    id: "cat_1",
    name: "Whole Spices",
    slug: "whole-spices",
    description: "Unground, sun-dried whole spices for maximum freshness and aroma.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    color: "#C15B2A",
    productCount: 12,
  },
  {
    id: "cat_2",
    name: "Ground Spices",
    slug: "ground-spices",
    description: "Finely milled spice powders ready for instant use in cooking.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
    color: "#8B4513",
    productCount: 10,
  },
  {
    id: "cat_3",
    name: "Fresh Herbs",
    slug: "fresh-herbs",
    description: "Dried aromatic herbs that preserve the essence of fresh-picked leaves.",
    image: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&q=80",
    color: "#2D5016",
    productCount: 9,
  },
  {
    id: "cat_4",
    name: "Spice Blends",
    slug: "spice-blends",
    description: "Expertly crafted spice mixes from traditional and modern recipes.",
    image: "https://images.unsplash.com/photo-1588619491790-25e98586eaad?w=600&q=80",
    color: "#7B3F00",
    productCount: 7,
  },
  {
    id: "cat_5",
    name: "Additives",
    slug: "additives",
    description: "Natural food additives, thickeners, and flavor enhancers.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
    color: "#4A6741",
    productCount: 6,
  },
  {
    id: "cat_6",
    name: "Specialty Salts",
    slug: "specialty-salts",
    description: "Artisanal and infused salts to elevate every dish.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    color: "#607D8B",
    productCount: 5,
  },
  {
    id: "cat_7",
    name: "Nature's Sweeteners",
    slug: "natures-sweeteners",
    description: "Pure honey, natural nut butters, and fruit-packed preserves.",
    image: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=600&q=80",
    color: "#D4A017",
    productCount: 4,
  },
  {
    id: "cat_8",
    name: "Beverages & Brews",
    slug: "beverages-brews",
    description: "Finest Kenyan coffee, specialty teas, and herbal infusions.",
    image: "https://images.unsplash.com/photo-1544787210-282744085f00?w=600&q=80",
    color: "#4E342E",
    productCount: 5,
  },
  {
    id: "cat_9",
    name: "Nuts & Dried Fruits",
    slug: "nuts-dried-fruits",
    description: "Premium selection of roasted nuts, raw nuts, and naturally sweet dried fruits.",
    image: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=600&q=80",
    color: "#D2691E",
    productCount: 4,
  },
  {
    id: "cat_10",
    name: "Cooking Oils",
    slug: "cooking-oils",
    description: "High-quality oils for everyday cooking, frying, dressings, and marinades.",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&q=80",
    color: "#DAA520",
    productCount: 4,
  },
];

// ─── Products ────────────────────────────────────────────────────────────────

export const products: Product[] = [
  {
    id: "prod_1",
    name: "Premium Cinnamon Sticks",
    slug: "premium-cinnamon-sticks",
    description:
      "Sourced from the highlands of Sri Lanka, our premium Ceylon cinnamon sticks are prized for their delicate, sweet flavour and thin, layered bark. Perfect for teas, desserts, curries, and mulled wines. Each stick is sun-dried to preserve its natural volatile oils.",
    shortDescription: "True Ceylon cinnamon, delicately sweet and aromatic.",
    price: 450,
    compareAtPrice: 600,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["cinnamon", "baking", "tea", "sweet"],
    images: [
      { id: "img_1a", url: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&q=80", alt: "Premium Cinnamon Sticks" },
      { id: "img_1b", url: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&q=80", alt: "Cinnamon sticks close up" },
    ],
    stock: 150,
    unit: "100g",
    origin: "Sri Lanka",
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-10",
  },
  {
    id: "prod_2",
    name: "Black Pepper (Tellicherry)",
    slug: "black-pepper-tellicherry",
    description:
      "Tellicherry black pepper is widely considered the world's finest. Larger berries are left on the vine longer to develop complex, fruity, aromatic heat. Use whole in a pepper mill or crack for rubs and sauces.",
    shortDescription: "World's finest large-berry black pepper, bold and aromatic.",
    price: 380,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["pepper", "spicy", "savory", "essential"],
    images: [
      { id: "img_2a", url: "https://images.unsplash.com/photo-1626202422002-39327f311f93?w=800&q=80", alt: "Tellicherry Black Pepper" },
      { id: "img_2b", url: "https://images.unsplash.com/photo-1621259182978-fbf93132d53d?w=800&q=80", alt: "Black Pepper" },
      { id: "img_2c", url: "https://images.unsplash.com/photo-1626202422002-39327f311f93?w=800&q=80", alt: "Tellicherry Black Pepper" },
    ],
    stock: 200,
    unit: "100g",
    origin: "India",
    rating: 4.9,
    reviewCount: 210,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-05",
  },
  {
    id: "prod_3",
    name: "Green Cardamom Pods",
    slug: "green-cardamom-pods",
    description:
      "Hand-picked green cardamom from Kerala, India. Known as the 'Queen of Spices', cardamom has a uniquely sweet, floral fragrance with menthol notes. Essential for chai, desserts, rice dishes, and meat marinades.",
    shortDescription: "Queen of Spices — floral, sweet, and intensely fragrant.",
    price: 890,
    compareAtPrice: 1100,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["cardamom", "chai", "baking", "sweet", "spicy"],
    images: [
      { id: "img_3a", url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80", alt: "Green Cardamom Pods" },
    ],
    stock: 80,
    unit: "50g",
    variations: [
      { id: "var_3a", name: "50g", price: 890, stock: 50 },
      { id: "var_3b", name: "100g", price: 1650, stock: 20 },
      { id: "var_3c", name: "200g", price: 3100, stock: 10 },
    ],
    origin: "India",
    rating: 4.7,
    reviewCount: 89,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-15",
  },
  {
    id: "prod_4",
    name: "Whole Cloves",
    slug: "whole-cloves",
    description:
      "Intensely aromatic dried flower buds from Zanzibar. Cloves have a powerful, warm, sweet, and slightly astringent flavour. Use in biryani, stews, mulled drinks, pickling, and baked goods.",
    shortDescription: "Zanzibar cloves — intensely aromatic and warming.",
    price: 320,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["cloves", "baking", "biryani", "warm"],
    images: [
      { id: "img_4a", url: "https://images.unsplash.com/photo-1609131009890-65bd0f972201?w=800&q=80", alt: "Whole Cloves" },
    ],
    stock: 120,
    unit: "100g",
    origin: "Zanzibar",
    rating: 4.6,
    reviewCount: 67,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-01",
  },
  {
    id: "prod_5",
    name: "Coriander Seeds",
    slug: "coriander-seeds",
    description:
      "Mild, nutty, and citrusy whole coriander seeds sourced from Ethiopia. Toast them lightly before grinding to unlock their full aromatic potential. A cornerstone of Indian, Middle Eastern, and African cuisines.",
    shortDescription: "Nutty, citrus-forward Ethiopian coriander seeds.",
    price: 180,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["coriander", "seeds", "curry", "mild"],
    images: [
      { id: "img_5a", url: "https://images.unsplash.com/photo-1599307734115-4422e5782025?w=800&q=80", alt: "Coriander Seeds" },
    ],
    stock: 300,
    unit: "200g",
    origin: "Ethiopia",
    rating: 4.5,
    reviewCount: 45,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-01",
  },
  {
    id: "prod_6",
    name: "Star Anise",
    slug: "star-anise",
    description:
      "Beautiful eight-pointed pods with a distinct, sweet liquorice flavour. Star anise is the star of Chinese five-spice, pho broth, and many slow-braised dishes. Also wonderful steeped in teas and warm drinks.",
    shortDescription: "Stunning pods with deep anise-liquorice notes.",
    price: 550,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["star anise", "pho", "chinese", "liquorice"],
    images: [
      { id: "img_6a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Star Anise" },
    ],
    stock: 90,
    unit: "75g",
    origin: "Vietnam",
    rating: 4.8,
    reviewCount: 55,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-05",
  },
  // Ground Spices
  {
    id: "prod_7",
    name: "Turmeric Powder",
    slug: "turmeric-powder",
    description:
      "Brilliant golden turmeric powder stone-ground from Alleppey variety roots, known for their exceptionally high curcumin content. Deep earthy flavour with a peppery edge. A staple in curries, golden milk, and health tonics.",
    shortDescription: "High-curcumin Alleppey turmeric — vivid colour, earthy heat.",
    price: 220,
    compareAtPrice: 280,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["turmeric", "health", "curry", "anti-inflammatory"],
    images: [
      { id: "img_7a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Turmeric Powder" },
    ],
    stock: 250,
    unit: "200g",
    origin: "India",
    rating: 4.9,
    reviewCount: 188,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-08",
  },
  {
    id: "prod_8",
    name: "Smoked Paprika",
    slug: "smoked-paprika",
    description:
      "Slow-smoked over oak fires and ground to a silky powder. Our Spanish smoked paprika (pimentón de la Vera) delivers a rich, smoky sweetness perfect for paellas, rubs, stews, and roasted vegetables.",
    shortDescription: "Spanish smoked paprika — deep, smoky, and intensely flavourful.",
    price: 350,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["paprika", "smoky", "spanish", "bbq"],
    images: [
      { id: "img_8a", url: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&q=80", alt: "Smoked Paprika" },
    ],
    stock: 160,
    unit: "100g",
    variations: [
      { id: "var_8a", name: "50g", price: 190, stock: 100 },
      { id: "var_8b", name: "100g", price: 350, stock: 60 },
    ],
    origin: "Spain",
    rating: 4.7,
    reviewCount: 102,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-01-20",
  },
  {
    id: "prod_9",
    name: "Cayenne Pepper",
    slug: "cayenne-pepper",
    description:
      "Pure, finely milled cayenne pepper with a clean, bright heat. Rated at 40,000 SHU, our cayenne adds fiery kick to sauces, marinades, rubs, and stews without muddying the flavour profile.",
    shortDescription: "Pure 40,000 SHU cayenne — bright, clean heat.",
    price: 190,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["cayenne", "hot", "chili", "heat"],
    images: [
      { id: "img_9a", url: "https://images.unsplash.com/photo-1627308595229-7830a5c91f9f?w=800&q=80", alt: "Cayenne Pepper" },
    ],
    stock: 200,
    unit: "100g",
    origin: "Mexico",
    rating: 4.6,
    reviewCount: 78,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-10",
  },
  {
    id: "prod_10",
    name: "Ground Cumin",
    slug: "ground-cumin",
    description:
      "Earthy, warm, and slightly smoky ground cumin from Rajasthan. Freshly milled from roasted seeds to maximise its complex, savoury aroma. Essential in Indian, Mexican, and Middle Eastern cooking.",
    shortDescription: "Freshly milled Rajasthani cumin — warm, earthy, and smoky.",
    price: 210,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["cumin", "earthy", "indian", "mexican"],
    images: [
      { id: "img_10a", url: "https://images.unsplash.com/photo-1533015582595-3ca446d3066e?w=800&q=80", alt: "Ground Cumin" },
    ],
    stock: 180,
    unit: "150g",
    origin: "India",
    rating: 4.8,
    reviewCount: 95,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-25",
  },
  // Herbs
  {
    id: "prod_11",
    name: "Organic Dried Rosemary",
    slug: "organic-dried-rosemary",
    description:
      "Certified organic rosemary from the Moroccan highlands, dried at low temperature to lock in its fragrant, pine-like perfume and savoury flavour. Excellent for roasted meats, potatoes, breads, and infused olive oils.",
    shortDescription: "Fragrant Moroccan organic rosemary, low-temperature dried.",
    price: 280,
    category: categories[2],
    categoryId: "cat_3",
    tags: ["rosemary", "herbs", "organic", "roasting"],
    images: [
      { id: "img_11a", url: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80", alt: "Dried Rosemary" },
    ],
    stock: 140,
    unit: "50g",
    origin: "Morocco",
    rating: 4.7,
    reviewCount: 63,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-05",
  },
  {
    id: "prod_12",
    name: "Dried Thyme",
    slug: "dried-thyme",
    description:
      "Fragrant Provençal thyme with earthy, minty, and slightly lemony notes. Indispensable in French and Mediterranean cooking — for stocks, stews, roasts, and the classic bouquet garni.",
    shortDescription: "Provençal dry thyme — earthy, minty, and versatile.",
    price: 240,
    category: categories[2],
    categoryId: "cat_3",
    tags: ["thyme", "herbs", "french", "mediterranean"],
    images: [
      { id: "img_12a", url: "https://images.unsplash.com/photo-1621871908119-295a8ce5b5cd?w=800&q=80", alt: "Dried Thyme" },
    ],
    stock: 110,
    unit: "40g",
    origin: "France",
    rating: 4.6,
    reviewCount: 41,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-15",
  },
  // Spice Blends
  {
    id: "prod_13",
    name: "Garam Masala",
    slug: "garam-masala",
    description:
      "A fragrant, warming blend of hand-toasted whole spices — cumin, coriander, cardamom, cloves, cinnamon, black pepper, and star anise — freshly ground to order. The soul of North Indian cuisine.",
    shortDescription: "Freshly toasted and ground North Indian garam masala.",
    price: 420,
    compareAtPrice: 520,
    category: categories[3],
    categoryId: "cat_4",
    tags: ["garam masala", "blend", "indian", "curry"],
    images: [
      { id: "img_13a", url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80", alt: "Garam Masala Blend" },
    ],
    stock: 130,
    unit: "100g",
    origin: "India",
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-12",
  },
  {
    id: "prod_14",
    name: "Berbere Spice Blend",
    slug: "berbere-spice-blend",
    description:
      "Ethiopia's iconic spice blend — a vibrant, deeply complex mix of chili, fenugreek, coriander, korarima (Ethiopian cardamom), rue, ajwain, and many more aromatics. The backbone of tibs, doro wat, and lentil stews.",
    shortDescription: "Ethiopia's iconic multi-spice blend — bold, warming, complex.",
    price: 480,
    category: categories[3],
    categoryId: "cat_4",
    tags: ["berbere", "ethiopian", "blend", "spicy"],
    images: [
      { id: "img_14a", url: "https://images.unsplash.com/photo-1599307734115-4422e5782025?w=800&q=80", alt: "Berbere Spice Blend" },
    ],
    stock: 75,
    unit: "100g",
    origin: "Ethiopia",
    rating: 4.8,
    reviewCount: 88,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-01-30",
  },
  {
    id: "prod_15",
    name: "Ras El Hanout",
    slug: "ras-el-hanout",
    description:
      "The crown jewel of Moroccan spice blending — 'top of the shop' in Arabic. Our blend includes over 25 premium spices, including dried rose petals, saffron, grains of paradise, cubeb pepper, and more.",
    shortDescription: "Moroccan luxury blend — over 25 premium spice ingredients.",
    price: 650,
    compareAtPrice: 800,
    category: categories[3],
    categoryId: "cat_4",
    tags: ["ras el hanout", "moroccan", "luxury", "blend"],
    images: [
      { id: "img_15a", url: "https://images.unsplash.com/photo-1638332128919-0941198595a8?w=800&q=80", alt: "Ras El Hanout" },
    ],
    stock: 60,
    unit: "75g",
    origin: "Morocco",
    rating: 4.9,
    reviewCount: 73,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-20",
  },
  // Additives
  {
    id: "prod_16",
    name: "Food-Grade Rose Water",
    slug: "food-grade-rose-water",
    description:
      "Pure, double-distilled rose water from Bulgarian Damask roses. Delicate floral aroma and flavour used in Middle Eastern desserts, lassis, rice dishes, and cocktails. No additives, 100% natural.",
    shortDescription: "Pure Bulgarian Damask rose water — 100% natural, double-distilled.",
    price: 340,
    category: categories[4],
    categoryId: "cat_5",
    tags: ["rose water", "desserts", "floral", "natural"],
    images: [
      { id: "img_16a", url: "https://images.unsplash.com/photo-1559235038-1ef7038e12c7?w=800&q=80", alt: "Rose Water" },
    ],
    stock: 95,
    unit: "200ml",
    origin: "Bulgaria",
    rating: 4.6,
    reviewCount: 39,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-01",
  },
  {
    id: "prod_17",
    name: "Saffron Threads",
    slug: "saffron-threads",
    description:
      "The world's most precious spice. Our Grade 1 saffron from Iran's Khorasan Province is hand-harvested, with deep red stigmas and maximum crocin content. Brings golden colour and honeyed, floral depth to rice, paella, biryani, and desserts.",
    shortDescription: "Grade 1 Khorasan saffron — world's most precious spice.",
    price: 2800,
    compareAtPrice: 3500,
    category: categories[4],
    categoryId: "cat_5",
    tags: ["saffron", "luxury", "golden", "premium"],
    images: [
      { id: "img_17a", url: "https://images.unsplash.com/photo-1567198179230-8bf05b060f08?w=800&q=80", alt: "Saffron Threads" },
    ],
    stock: 30,
    unit: "1g",
    origin: "Iran",
    rating: 5.0,
    reviewCount: 47,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-01",
  },
  {
    id: "prod_18",
    name: "Vanilla Beans (Grade A)",
    slug: "vanilla-beans-grade-a",
    description:
      "Plump, oil-rich Grade A Bourbon vanilla beans from Madagascar. Each bean is loaded with thousands of vanilla caviar seeds. Perfect for custards, ice cream, cakes, and any recipe where real vanilla flavour matters.",
    shortDescription: "Plump Madagascar Bourbon Grade A vanilla beans.",
    price: 1200,
    compareAtPrice: 1500,
    category: categories[4],
    categoryId: "cat_5",
    tags: ["vanilla", "baking", "desserts", "premium"],
    images: [
      { id: "img_18a", url: "https://images.unsplash.com/photo-1559235038-1ef7038e12c7?w=800&q=80", alt: "Vanilla Beans" },
    ],
    stock: 55,
    unit: "2 pods",
    origin: "Madagascar",
    rating: 4.9,
    reviewCount: 82,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-18",
  },
  // Specialty Salts
  {
    id: "prod_19",
    name: "Himalayan Pink Salt (Fine)",
    slug: "himalayan-pink-salt-fine",
    description:
      "Ancient mineral-rich salt from the Khewra Salt Mine in Pakistan. 84 trace minerals give it a subtle, complex flavour and beautiful rose-pink colour. Finely ground for everyday cooking, seasoning, and baking.",
    shortDescription: "84-mineral ancient pink salt, finely ground.",
    price: 280,
    category: categories[5],
    categoryId: "cat_6",
    tags: ["pink salt", "himalayan", "mineral", "cooking"],
    images: [
      { id: "img_19a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Himalayan Pink Salt" },
    ],
    stock: 220,
    unit: "500g",
    origin: "Pakistan",
    rating: 4.5,
    reviewCount: 110,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-01",
  },
  {
    id: "prod_20",
    name: "Smoked Sea Salt",
    slug: "smoked-sea-salt",
    description:
      "Hand-harvested Atlantic sea salt cold-smoked over oak and cherry wood for 48 hours. Adds incredible depth and smoky complexity to finished dishes, grilled meats, salads, and even chocolate desserts.",
    shortDescription: "Oak & cherry cold-smoked Atlantic sea salt — 48-hour process.",
    price: 420,
    category: categories[5],
    categoryId: "cat_6",
    tags: ["smoked salt", "bbq", "finishing", "oak"],
    images: [
      { id: "img_20a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Smoked Sea Salt" },
    ],
    stock: 85,
    unit: "200g",
    origin: "Portugal",
    rating: 4.7,
    reviewCount: 54,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-08",
  },
  // Nature's Sweeteners
  {
    id: "prod_21",
    name: "Pure Wildflower Honey",
    slug: "pure-wildflower-honey",
    description: "Unfiltered, raw wildflower honey from the Rift Valley. Rich in antioxidants and natural enzymes with a complex, floral profile that changes with the seasons.",
    shortDescription: "Raw, unfiltered Rift Valley wildflower honey.",
    price: 650,
    category: categories[6],
    categoryId: "cat_7",
    tags: ["honey", "sweetener", "natural", "raw"],
    images: [
      { id: "img_21a", url: "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80", alt: "Pure Wildflower Honey" },
    ],
    stock: 100,
    unit: "500g",
    origin: "Kenya",
    rating: 4.9,
    reviewCount: 42,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-10",
  },
  {
    id: "prod_22",
    name: "Artisan Peanut Butter",
    slug: "artisan-peanut-butter",
    description: "Small-batch peanut butter made from roasted Kenyan peanuts and a pinch of sea salt. No added sugars, oils, or preservatives — just pure, creamy goodness.",
    shortDescription: "Pure roasted peanut butter — no additives, just peanuts.",
    price: 480,
    category: categories[6],
    categoryId: "cat_7",
    tags: ["peanut butter", "spread", "protein", "natural"],
    images: [
      { id: "img_22a", url: "https://images.unsplash.com/photo-1590301157890-4810ed352733?w=800&q=80", alt: "Artisan Peanut Butter" },
    ],
    stock: 120,
    unit: "400g",
    origin: "Kenya",
    rating: 4.8,
    reviewCount: 29,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-12",
  },
  {
    id: "prod_23",
    name: "Zesta Mixed Fruit Jam",
    slug: "zesta-mixed-fruit-jam",
    description: "The classic Kenyan favorite. A perfect blend of tropical fruits, great for breakfast toast, pancakes, or baking. A household staple known for its consistent quality.",
    shortDescription: "Classic Kenyan mixed fruit jam — a breakfast essential.",
    price: 250,
    category: categories[6],
    categoryId: "cat_7",
    tags: ["jam", "spread", "fruit", "zesta"],
    images: [
      { id: "img_23a", url: "https://images.unsplash.com/photo-1631515243349-e0cb75fb8d3a?w=800&q=80", alt: "Mixed Fruit Jam" },
    ],
    stock: 200,
    unit: "500g",
    origin: "Kenya",
    rating: 4.5,
    reviewCount: 95,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-10",
  },
  // Beverages & Brews
  {
    id: "prod_24",
    name: "AA Grade Kenyan Coffee",
    slug: "aa-grade-kenyan-coffee",
    description: "World-renowned AA Grade coffee from the slopes of Mt. Kenya. Known for its intense flavor, full body, and pleasant aroma with notes of bright citrus and a clean finish.",
    shortDescription: "Premium AA Grade Kenyan coffee — bold, aromatic, and bright.",
    price: 850,
    category: categories[7],
    categoryId: "cat_8",
    tags: ["coffee", "kenyan", "beverage", "premium"],
    images: [
      { id: "img_24a", url: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&q=80", alt: "Kenyan Coffee" },
    ],
    stock: 150,
    unit: "250g",
    variations: [
      { id: "var_24a", name: "250g Ground", price: 850, stock: 100 },
      { id: "var_24b", name: "250g Whole Bean", price: 850, stock: 50 },
      { id: "var_24c", name: "500g Ground", price: 1600, stock: 30 },
    ],
    origin: "Kenya",
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-05",
  },
  {
    id: "prod_25",
    name: "Dried Hibiscus Flowers",
    slug: "dried-hibiscus-flowers",
    description: "Whole dried hibiscus calyces (Zobo/Bissap). Makes a refreshing, deep red infusion with a tart, cranberry-like flavor. Rich in Vitamin C and naturally caffeine-free.",
    shortDescription: "Whole dried hibiscus flowers — tart, vibrant, and caffeine-free.",
    price: 320,
    category: categories[7],
    categoryId: "cat_8",
    tags: ["hibiscus", "tea", "herbal", "infusion"],
    images: [
      { id: "img_25a", url: "https://images.unsplash.com/photo-1511200057088-25fc5016e3ec?w=800&q=80", alt: "Hibiscus Flowers" },
    ],
    stock: 200,
    unit: "100g",
    origin: "Egypt",
    rating: 4.7,
    reviewCount: 52,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-01",
  },
  {
    id: "prod_26",
    name: "Organic Lemongrass Tea",
    slug: "organic-lemongrass-tea",
    description: "Dried hand-cut lemongrass stalks. Delivers a clean, citrusy aroma and a mild, soothing flavor. Perfect as a standalone wellness tea or blended with ginger and honey.",
    shortDescription: "Pure organic lemongrass — fresh, citrusy, and soothing.",
    price: 280,
    category: categories[7],
    categoryId: "cat_8",
    tags: ["lemongrass", "tea", "herbal", "detox"],
    images: [
      { id: "img_26a", url: "https://images.unsplash.com/photo-1606787366850-de6330128bfc?w=800&q=80", alt: "Lemongrass Tea" },
    ],
    stock: 180,
    unit: "50g",
    origin: "Kenya",
    rating: 4.6,
    reviewCount: 38,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-15",
  },
  {
    id: "prod_27",
    name: "Pure Soya Powder",
    slug: "pure-soya-powder",
    description: "Finely ground roasted soybeans. A nutrient-dense, high-protein alternative to dairy milk. Great for porridges, smoothies, or as a healthy beverage base.",
    shortDescription: "Roasted soya powder — high protein, dairy-free nutritional base.",
    price: 350,
    category: categories[7],
    categoryId: "cat_8",
    tags: ["soya", "protein", "beverage", "healthy"],
    images: [
      { id: "img_27a", url: "https://images.unsplash.com/photo-1589133038661-80a9da5e8964?w=800&q=80", alt: "Soya Powder" },
    ],
    stock: 140,
    unit: "500g",
    origin: "Kenya",
    rating: 4.4,
    reviewCount: 45,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-05",
  },
  // Nuts
  {
    id: "prod_28",
    name: "Roasted Groundnuts (Peanuts)",
    slug: "roasted-groundnuts",
    description: "Perfectly roasted, crunchy Kenyan groundnuts. Enjoy them as a healthy snack or use them to make fresh peanut butter.",
    shortDescription: "Crunchy, roasted Kenyan groundnuts.",
    price: 350,
    category: categories[8],
    categoryId: "cat_9",
    tags: ["nuts", "snacks", "peanuts", "roasted"],
    images: [
      { id: "img_28a", url: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80", alt: "Roasted Groundnuts" },
    ],
    stock: 250,
    unit: "500g",
    origin: "Kenya",
    rating: 4.8,
    reviewCount: 42,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    createdAt: "2025-03-20",
  },
  {
    id: "prod_29",
    name: "Raw Cashew Nuts",
    slug: "raw-cashew-nuts",
    description: "Premium large, raw cashew nuts sourced directly from the coast. Sweet, buttery, and perfect for roasting, baking, or cooking.",
    shortDescription: "Premium large raw cashew nuts.",
    price: 1200,
    compareAtPrice: 1500,
    category: categories[8],
    categoryId: "cat_9",
    tags: ["cashews", "nuts", "raw", "baking"],
    images: [
      { id: "img_29a", url: "https://images.unsplash.com/photo-1536591375315-99d949bd5a96?w=800&q=80", alt: "Raw Cashew Nuts" },
    ],
    stock: 80,
    unit: "250g",
    origin: "Tanzania",
    rating: 4.9,
    reviewCount: 65,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-21",
  },
  {
    id: "prod_30",
    name: "Macadamia Nuts",
    slug: "macadamia-nuts",
    description: "Rich and buttery macadamia nuts. Grown in the Kenyan highlands, these nuts are a luxurious snack loaded with healthy fats.",
    shortDescription: "Rich and buttery Kenyan macadamia nuts.",
    price: 1500,
    category: categories[8],
    categoryId: "cat_9",
    tags: ["macadamia", "nuts", "healthy", "snack"],
    images: [
      { id: "img_30a", url: "https://images.unsplash.com/photo-1610444538928-8547ca5d09f6?w=800&q=80", alt: "Macadamia Nuts" },
    ],
    stock: 50,
    unit: "250g",
    origin: "Kenya",
    rating: 5.0,
    reviewCount: 22,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-21",
  },
  {
    id: "prod_31",
    name: "Premium Dates (Safawi)",
    slug: "premium-dates-safawi",
    description: "Soft, chewy, and naturally sweet Safawi dates. Perfect as a natural sugar substitute, snack, or addition to your morning smoothies.",
    shortDescription: "Soft, naturally sweet dark dates.",
    price: 850,
    category: categories[8],
    categoryId: "cat_9",
    tags: ["dates", "sweet", "dried fruits", "snack"],
    images: [
      { id: "img_31a", url: "https://images.unsplash.com/photo-1596431267426-1049c636d1b8?w=800&q=80", alt: "Premium Dates" },
    ],
    stock: 120,
    unit: "500g",
    origin: "Saudi Arabia",
    rating: 4.8,
    reviewCount: 34,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    createdAt: "2025-03-22",
  },
  // Cooking Oils
  {
    id: "prod_32",
    name: "Elianto Pure Corn Oil",
    slug: "elianto-pure-corn-oil",
    description: "100% pure corn oil, triple-refined for a clean taste and high smoke point. Ideal for deep frying, baking, and everyday cooking.",
    shortDescription: "Pure, cholesterol-free corn oil for everyday cooking.",
    price: 1050,
    category: categories[9],
    categoryId: "cat_10",
    tags: ["oil", "corn oil", "elianto", "cooking"],
    images: [
      { id: "img_32a", url: "https://images.unsplash.com/photo-1620025983790-25e4c6020556?w=800&q=80", alt: "Corn Oil" },
    ],
    stock: 300,
    unit: "2 Litres",
    origin: "Kenya",
    rating: 4.6,
    reviewCount: 110,
    isFeatured: false,
    isNew: true,
    isBestSeller: true,
    createdAt: "2025-03-22",
  },
  {
    id: "prod_33",
    name: "Golden Premium Sunflower Oil",
    slug: "golden-sunflower-oil",
    description: "Light and healthy sunflower oil rich in Vitamin E. Excellent for shallow frying, salads, and marinades without overpowering your food's flavor.",
    shortDescription: "Light sunflower oil, rich in Vitamin E.",
    price: 950,
    category: categories[9],
    categoryId: "cat_10",
    tags: ["oil", "sunflower oil", "cooking"],
    images: [
      { id: "img_33a", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80", alt: "Sunflower Oil" },
    ],
    stock: 250,
    unit: "2 Litres",
    origin: "Kenya",
    rating: 4.7,
    reviewCount: 88,
    isFeatured: true,
    isNew: true,
    isBestSeller: true,
    createdAt: "2025-03-22",
  },
  {
    id: "prod_34",
    name: "Extra Virgin Olive Oil",
    slug: "extra-virgin-olive-oil",
    description: "Cold-pressed extra virgin olive oil made from premium Mediterranean olives. Earthy, slightly peppery, and perfect for dressings and finishing dishes.",
    shortDescription: "Cold-pressed extra virgin olive oil.",
    price: 1800,
    category: categories[9],
    categoryId: "cat_10",
    tags: ["oil", "olive oil", "virgin", "dressing"],
    images: [
      { id: "img_34a", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=800&q=80", alt: "Olive Oil" },
    ],
    stock: 80,
    unit: "750ml",
    origin: "Italy",
    rating: 4.9,
    reviewCount: 45,
    isFeatured: true,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-22",
  },
  {
    id: "prod_35",
    name: "Pure Palm Oil",
    slug: "pure-palm-oil",
    description: "Unrefined red palm oil, rich in antioxidants and vital for authentic West African and traditional recipes. Adds a brilliant color and rich earthy flavor.",
    shortDescription: "Unrefined red palm oil for authentic cooking.",
    price: 750,
    category: categories[9],
    categoryId: "cat_10",
    tags: ["oil", "palm oil", "traditional", "cooking"],
    images: [
      { id: "img_35a", url: "https://images.unsplash.com/photo-1620025983790-25e4c6020556?w=800&q=80", alt: "Palm Oil" },
    ],
    stock: 100,
    unit: "1 Litre",
    origin: "Ghana",
    rating: 4.5,
    reviewCount: 30,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-22",
  },
];

// ─── Reviews ──────────────────────────────────────────────────────────────────

export const reviews: Review[] = [
  {
    id: "rev_1",
    productId: "prod_1",
    author: "Amina Ochieng",
    rating: 5,
    title: "Absolutely incredible quality",
    body: "I've been buying cinnamon for years and this is hands-down the best I've ever had. The aroma fills the whole kitchen when you open the bag. Will never buy supermarket cinnamon again!",
    createdAt: "2025-02-15",
    verified: true,
  },
  {
    id: "rev_2",
    productId: "prod_1",
    author: "James Kariuki",
    rating: 5,
    title: "A game changer for my chai",
    body: "My morning chai has never been better. Real Ceylon cinnamon has such a different flavour from the cassia you get in shops. Totally worth it.",
    createdAt: "2025-03-01",
    verified: true,
  },
  {
    id: "rev_3",
    productId: "prod_7",
    author: "Fatuma Hassan",
    rating: 5,
    title: "Vibrant colour, deep flavour",
    body: "The colour of this turmeric is stunning — a deep, saturated gold. It made my curries look like restaurant food. Fast delivery too!",
    createdAt: "2025-02-28",
    verified: true,
  },
  {
    id: "rev_4",
    productId: "prod_13",
    author: "David Mwangi",
    rating: 5,
    title: "Freshest garam masala I've ever tasted",
    body: "You can genuinely tell this was freshly ground. The fragrance is incredible and it transforms every dish. I ordered 3 packs this time.",
    createdAt: "2025-03-05",
    verified: true,
  },
  {
    id: "rev_5",
    productId: "prod_17",
    author: "Layla Al-Amin",
    rating: 5,
    title: "Genuine Grade 1 — worth every shilling",
    body: "I was hesitant given the price but this is real saffron. A tiny pinch makes the most beautifully golden, fragrant rice. Superb quality.",
    createdAt: "2025-03-10",
    verified: true,
  },
  {
    id: "rev_6",
    productId: "prod_2",
    author: "Grace Wanjiku",
    rating: 5,
    title: "The best pepper mill fill",
    body: "These Tellicherry peppercorns are large, aromatic and have incredible flavour. My whole family has noticed how much better the food tastes!",
    createdAt: "2025-02-20",
    verified: true,
  },
];

// ─── Users ───────────────────────────────────────────────────────────────────

export const users: User[] = [
  {
    id: "user_1",
    name: "Amina Ochieng",
    email: "amina@example.com",
    phone: "+254 712 345 678",
    role: "customer",
    createdAt: "2024-11-01",
    orderCount: 5,
    totalSpent: 12450,
  },
  {
    id: "user_2",
    name: "James Kariuki",
    email: "james@example.com",
    phone: "+254 721 234 567",
    role: "customer",
    createdAt: "2024-12-03",
    orderCount: 2,
    totalSpent: 3800,
  },
  {
    id: "user_3",
    name: "Fatuma Hassan",
    email: "fatuma@example.com",
    phone: "+254 733 456 789",
    role: "customer",
    createdAt: "2025-01-15",
    orderCount: 3,
    totalSpent: 6700,
  },
  {
    id: "user_4",
    name: "Admin User",
    email: "admin@glowspice.co.ke",
    role: "admin",
    createdAt: "2024-10-01",
  },
  {
    id: "user_5",
    name: "Grace Wanjiku",
    email: "grace@example.com",
    phone: "+254 742 567 890",
    role: "customer",
    createdAt: "2025-01-22",
    orderCount: 1,
    totalSpent: 1850,
  },
  {
    id: "user_6",
    name: "David Mwangi",
    email: "david@example.com",
    phone: "+254 751 678 901",
    role: "customer",
    createdAt: "2025-02-08",
    orderCount: 4,
    totalSpent: 9250,
  },
];

// ─── Orders ──────────────────────────────────────────────────────────────────

export const orders: Order[] = [
  {
    id: "ord_1",
    orderNumber: "GS-2025-0001",
    customerId: "user_1",
    customer: users[0],
    items: [
      { product: products[0], quantity: 2, unitPrice: 450, subtotal: 900 },
      { product: products[6], quantity: 1, unitPrice: 220, subtotal: 220 },
    ],
    status: "delivered",
    shippingAddress: {
      fullName: "Amina Ochieng",
      email: "amina@example.com",
      phone: "+254 712 345 678",
      address: "14 Garden Estate Road",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00100",
      country: "Kenya",
    },
    subtotal: 1120,
    shippingCost: 200,
    tax: 180,
    total: 1500,
    paymentMethod: "M-Pesa",
    createdAt: "2025-02-10",
    updatedAt: "2025-02-14",
  },
  {
    id: "ord_2",
    orderNumber: "GS-2025-0002",
    customerId: "user_2",
    customer: users[1],
    items: [
      { product: products[12], quantity: 1, unitPrice: 420, subtotal: 420 },
      { product: products[14], quantity: 1, unitPrice: 650, subtotal: 650 },
    ],
    status: "shipped",
    shippingAddress: {
      fullName: "James Kariuki",
      email: "james@example.com",
      phone: "+254 721 234 567",
      address: "Westlands Business Park, Suite 4B",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00800",
      country: "Kenya",
    },
    subtotal: 1070,
    shippingCost: 200,
    tax: 171,
    total: 1441,
    paymentMethod: "Card",
    createdAt: "2025-03-01",
    updatedAt: "2025-03-03",
  },
  {
    id: "ord_3",
    orderNumber: "GS-2025-0003",
    customerId: "user_3",
    customer: users[2],
    items: [
      { product: products[16], quantity: 1, unitPrice: 2800, subtotal: 2800 },
    ],
    status: "processing",
    shippingAddress: {
      fullName: "Fatuma Hassan",
      email: "fatuma@example.com",
      phone: "+254 733 456 789",
      address: "Mombasa Road, Mlolongo",
      city: "Machakos",
      county: "Machakos",
      postalCode: "90100",
      country: "Kenya",
    },
    subtotal: 2800,
    shippingCost: 300,
    tax: 448,
    total: 3548,
    paymentMethod: "M-Pesa",
    createdAt: "2025-03-08",
    updatedAt: "2025-03-08",
  },
  {
    id: "ord_4",
    orderNumber: "GS-2025-0004",
    customerId: "user_5",
    customer: users[4],
    items: [
      { product: products[1], quantity: 2, unitPrice: 380, subtotal: 760 },
      { product: products[9], quantity: 1, unitPrice: 210, subtotal: 210 },
      { product: products[10], quantity: 1, unitPrice: 280, subtotal: 280 },
    ],
    status: "pending",
    shippingAddress: {
      fullName: "Grace Wanjiku",
      email: "grace@example.com",
      phone: "+254 742 567 890",
      address: "Karen, Bogani East Rd",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00502",
      country: "Kenya",
    },
    subtotal: 1250,
    shippingCost: 200,
    tax: 200,
    total: 1650,
    paymentMethod: "Card",
    createdAt: "2025-03-12",
    updatedAt: "2025-03-12",
  },
  {
    id: "ord_5",
    orderNumber: "GS-2025-0005",
    customerId: "user_6",
    customer: users[5],
    items: [
      { product: products[3], quantity: 3, unitPrice: 320, subtotal: 960 },
      { product: products[4], quantity: 2, unitPrice: 180, subtotal: 360 },
      { product: products[13], quantity: 1, unitPrice: 480, subtotal: 480 },
    ],
    status: "confirmed",
    shippingAddress: {
      fullName: "David Mwangi",
      email: "david@example.com",
      phone: "+254 751 678 901",
      address: "Kilimani, Argwings Kodhek Rd",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00200",
      country: "Kenya",
    },
    subtotal: 1800,
    shippingCost: 200,
    tax: 288,
    total: 2288,
    paymentMethod: "M-Pesa",
    createdAt: "2025-03-13",
    updatedAt: "2025-03-13",
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalRevenue: 483250,
  totalOrders: 147,
  totalCustomers: 89,
  totalProducts: products.length,
  revenueChange: 18.4,
  ordersChange: 12.2,
  customersChange: 24.7,
  recentOrders: orders,
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.isBestSeller);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getProductReviews(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getOrderById(id: string): Order | undefined {
  return orders.find((o) => o.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}
