import type {
  Category,
  Product,
  Review,
  Order,
  User,
  DashboardStats,
} from "./types";

// ─── Categories ──────────────────────────────────────────────────────────────

export const categories: Category[] = [
  {
    id: "cat_1",
    name: "Whole Spices",
    slug: "whole-spices",
    description: "Unground, sun-dried whole spices for maximum freshness and aroma.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    color: "#C15B2A",
    productCount: 12,
  },
  {
    id: "cat_2",
    name: "Ground Spices",
    slug: "ground-spices",
    description: "Finely milled spice powders ready for instant use in cooking.",
    image: "https://images.unsplash.com/photo-1532336414038-cf190504f475?w=600&q=80",
    color: "#8B4513",
    productCount: 10,
  },
  {
    id: "cat_3",
    name: "Fresh Herbs",
    slug: "fresh-herbs",
    description: "Dried aromatic herbs that preserve the essence of fresh-picked leaves.",
    image: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=600&q=80",
    color: "#2D5016",
    productCount: 9,
  },
  {
    id: "cat_4",
    name: "Spice Blends",
    slug: "spice-blends",
    description: "Expertly crafted spice mixes from traditional and modern recipes.",
    image: "https://images.unsplash.com/photo-1583394293214-5c3b93e673ac?w=600&q=80",
    color: "#7B3F00",
    productCount: 7,
  },
  {
    id: "cat_5",
    name: "Additives",
    slug: "additives",
    description: "Natural food additives, thickeners, and flavor enhancers.",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&q=80",
    color: "#4A6741",
    productCount: 6,
  },
  {
    id: "cat_6",
    name: "Specialty Salts",
    slug: "specialty-salts",
    description: "Artisanal and infused salts to elevate every dish.",
    image: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&q=80",
    color: "#607D8B",
    productCount: 5,
  },
];

// ─── Products ────────────────────────────────────────────────────────────────

export const products: Product[] = [
  {
    id: "prod_1",
    name: "Premium Cinnamon Sticks",
    slug: "premium-cinnamon-sticks",
    description:
      "Sourced from the highlands of Sri Lanka, our premium Ceylon cinnamon sticks are prized for their delicate, sweet flavour and thin, layered bark. Perfect for teas, desserts, curries, and mulled wines. Each stick is sun-dried to preserve its natural volatile oils.",
    shortDescription: "True Ceylon cinnamon, delicately sweet and aromatic.",
    price: 450,
    compareAtPrice: 600,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["cinnamon", "baking", "tea", "sweet"],
    images: [
      { id: "img_1a", url: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&q=80", alt: "Premium Cinnamon Sticks" },
      { id: "img_1b", url: "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?w=800&q=80", alt: "Cinnamon sticks close up" },
    ],
    stock: 150,
    unit: "100g",
    origin: "Sri Lanka",
    rating: 4.8,
    reviewCount: 124,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-10",
  },
  {
    id: "prod_2",
    name: "Black Pepper (Tellicherry)",
    slug: "black-pepper-tellicherry",
    description:
      "Tellicherry black pepper is widely considered the world's finest. Larger berries are left on the vine longer to develop complex, fruity, aromatic heat. Use whole in a pepper mill or crack for rubs and sauces.",
    shortDescription: "World's finest large-berry black pepper, bold and aromatic.",
    price: 380,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["pepper", "spicy", "savory", "essential"],
    images: [
      { id: "img_2a", url: "https://images.unsplash.com/photo-1508747703725-719777637510?w=800&q=80", alt: "Tellicherry Black Pepper" },
    ],
    stock: 200,
    unit: "100g",
    origin: "India",
    rating: 4.9,
    reviewCount: 210,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-05",
  },
  {
    id: "prod_3",
    name: "Green Cardamom Pods",
    slug: "green-cardamom-pods",
    description:
      "Hand-picked green cardamom from Kerala, India. Known as the 'Queen of Spices', cardamom has a uniquely sweet, floral fragrance with menthol notes. Essential for chai, desserts, rice dishes, and meat marinades.",
    shortDescription: "Queen of Spices — floral, sweet, and intensely fragrant.",
    price: 890,
    compareAtPrice: 1100,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["cardamom", "chai", "baking", "sweet", "spicy"],
    images: [
      { id: "img_3a", url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80", alt: "Green Cardamom Pods" },
    ],
    stock: 80,
    unit: "50g",
    origin: "India",
    rating: 4.7,
    reviewCount: 89,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-15",
  },
  {
    id: "prod_4",
    name: "Whole Cloves",
    slug: "whole-cloves",
    description:
      "Intensely aromatic dried flower buds from Zanzibar. Cloves have a powerful, warm, sweet, and slightly astringent flavour. Use in biryani, stews, mulled drinks, pickling, and baked goods.",
    shortDescription: "Zanzibar cloves — intensely aromatic and warming.",
    price: 320,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["cloves", "baking", "biryani", "warm"],
    images: [
      { id: "img_4a", url: "https://images.unsplash.com/photo-1609131009890-65bd0f972201?w=800&q=80", alt: "Whole Cloves" },
    ],
    stock: 120,
    unit: "100g",
    origin: "Zanzibar",
    rating: 4.6,
    reviewCount: 67,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-01",
  },
  {
    id: "prod_5",
    name: "Coriander Seeds",
    slug: "coriander-seeds",
    description:
      "Mild, nutty, and citrusy whole coriander seeds sourced from Ethiopia. Toast them lightly before grinding to unlock their full aromatic potential. A cornerstone of Indian, Middle Eastern, and African cuisines.",
    shortDescription: "Nutty, citrus-forward Ethiopian coriander seeds.",
    price: 180,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["coriander", "seeds", "curry", "mild"],
    images: [
      { id: "img_5a", url: "https://images.unsplash.com/photo-1532336414038-cf190504f475?w=800&q=80", alt: "Coriander Seeds" },
    ],
    stock: 300,
    unit: "200g",
    origin: "Ethiopia",
    rating: 4.5,
    reviewCount: 45,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-01",
  },
  {
    id: "prod_6",
    name: "Star Anise",
    slug: "star-anise",
    description:
      "Beautiful eight-pointed pods with a distinct, sweet liquorice flavour. Star anise is the star of Chinese five-spice, pho broth, and many slow-braised dishes. Also wonderful steeped in teas and warm drinks.",
    shortDescription: "Stunning pods with deep anise-liquorice notes.",
    price: 550,
    category: categories[0],
    categoryId: "cat_1",
    tags: ["star anise", "pho", "chinese", "liquorice"],
    images: [
      { id: "img_6a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Star Anise" },
    ],
    stock: 90,
    unit: "75g",
    origin: "Vietnam",
    rating: 4.8,
    reviewCount: 55,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-05",
  },
  // Ground Spices
  {
    id: "prod_7",
    name: "Turmeric Powder",
    slug: "turmeric-powder",
    description:
      "Brilliant golden turmeric powder stone-ground from Alleppey variety roots, known for their exceptionally high curcumin content. Deep earthy flavour with a peppery edge. A staple in curries, golden milk, and health tonics.",
    shortDescription: "High-curcumin Alleppey turmeric — vivid colour, earthy heat.",
    price: 220,
    compareAtPrice: 280,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["turmeric", "health", "curry", "anti-inflammatory"],
    images: [
      { id: "img_7a", url: "https://images.unsplash.com/photo-1615485247094-15b4e104e8cb?w=800&q=80", alt: "Turmeric Powder" },
    ],
    stock: 250,
    unit: "200g",
    origin: "India",
    rating: 4.9,
    reviewCount: 188,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-08",
  },
  {
    id: "prod_8",
    name: "Smoked Paprika",
    slug: "smoked-paprika",
    description:
      "Slow-smoked over oak fires and ground to a silky powder. Our Spanish smoked paprika (pimentón de la Vera) delivers a rich, smoky sweetness perfect for paellas, rubs, stews, and roasted vegetables.",
    shortDescription: "Spanish smoked paprika — deep, smoky, and intensely flavourful.",
    price: 350,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["paprika", "smoky", "spanish", "bbq"],
    images: [
      { id: "img_8a", url: "https://images.unsplash.com/photo-1506368249639-73a05d6f6488?w=800&q=80", alt: "Smoked Paprika" },
    ],
    stock: 160,
    unit: "100g",
    origin: "Spain",
    rating: 4.7,
    reviewCount: 102,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-01-20",
  },
  {
    id: "prod_9",
    name: "Cayenne Pepper",
    slug: "cayenne-pepper",
    description:
      "Pure, finely milled cayenne pepper with a clean, bright heat. Rated at 40,000 SHU, our cayenne adds fiery kick to sauces, marinades, rubs, and stews without muddying the flavour profile.",
    shortDescription: "Pure 40,000 SHU cayenne — bright, clean heat.",
    price: 190,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["cayenne", "hot", "chili", "heat"],
    images: [
      { id: "img_9a", url: "https://images.unsplash.com/photo-1583394293214-5c3b93e673ac?w=800&q=80", alt: "Cayenne Pepper" },
    ],
    stock: 200,
    unit: "100g",
    origin: "Mexico",
    rating: 4.6,
    reviewCount: 78,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-10",
  },
  {
    id: "prod_10",
    name: "Ground Cumin",
    slug: "ground-cumin",
    description:
      "Earthy, warm, and slightly smoky ground cumin from Rajasthan. Freshly milled from roasted seeds to maximise its complex, savoury aroma. Essential in Indian, Mexican, and Middle Eastern cooking.",
    shortDescription: "Freshly milled Rajasthani cumin — warm, earthy, and smoky.",
    price: 210,
    category: categories[1],
    categoryId: "cat_2",
    tags: ["cumin", "earthy", "indian", "mexican"],
    images: [
      { id: "img_10a", url: "https://images.unsplash.com/photo-1532336414038-cf190504f475?w=800&q=80", alt: "Ground Cumin" },
    ],
    stock: 180,
    unit: "150g",
    origin: "India",
    rating: 4.8,
    reviewCount: 95,
    isFeatured: false,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-25",
  },
  // Herbs
  {
    id: "prod_11",
    name: "Organic Dried Rosemary",
    slug: "organic-dried-rosemary",
    description:
      "Certified organic rosemary from the Moroccan highlands, dried at low temperature to lock in its fragrant, pine-like perfume and savoury flavour. Excellent for roasted meats, potatoes, breads, and infused olive oils.",
    shortDescription: "Fragrant Moroccan organic rosemary, low-temperature dried.",
    price: 280,
    category: categories[2],
    categoryId: "cat_3",
    tags: ["rosemary", "herbs", "organic", "roasting"],
    images: [
      { id: "img_11a", url: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?w=800&q=80", alt: "Dried Rosemary" },
    ],
    stock: 140,
    unit: "50g",
    origin: "Morocco",
    rating: 4.7,
    reviewCount: 63,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-05",
  },
  {
    id: "prod_12",
    name: "Dried Thyme",
    slug: "dried-thyme",
    description:
      "Fragrant Provençal thyme with earthy, minty, and slightly lemony notes. Indispensable in French and Mediterranean cooking — for stocks, stews, roasts, and the classic bouquet garni.",
    shortDescription: "Provençal dry thyme — earthy, minty, and versatile.",
    price: 240,
    category: categories[2],
    categoryId: "cat_3",
    tags: ["thyme", "herbs", "french", "mediterranean"],
    images: [
      { id: "img_12a", url: "https://images.unsplash.com/photo-1621871908119-295a8ce5b5cd?w=800&q=80", alt: "Dried Thyme" },
    ],
    stock: 110,
    unit: "40g",
    origin: "France",
    rating: 4.6,
    reviewCount: 41,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-15",
  },
  // Spice Blends
  {
    id: "prod_13",
    name: "Garam Masala",
    slug: "garam-masala",
    description:
      "A fragrant, warming blend of hand-toasted whole spices — cumin, coriander, cardamom, cloves, cinnamon, black pepper, and star anise — freshly ground to order. The soul of North Indian cuisine.",
    shortDescription: "Freshly toasted and ground North Indian garam masala.",
    price: 420,
    compareAtPrice: 520,
    category: categories[3],
    categoryId: "cat_4",
    tags: ["garam masala", "blend", "indian", "curry"],
    images: [
      { id: "img_13a", url: "https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=800&q=80", alt: "Garam Masala Blend" },
    ],
    stock: 130,
    unit: "100g",
    origin: "India",
    rating: 4.9,
    reviewCount: 156,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-12",
  },
  {
    id: "prod_14",
    name: "Berbere Spice Blend",
    slug: "berbere-spice-blend",
    description:
      "Ethiopia's iconic spice blend — a vibrant, deeply complex mix of chili, fenugreek, coriander, korarima (Ethiopian cardamom), rue, ajwain, and many more aromatics. The backbone of tibs, doro wat, and lentil stews.",
    shortDescription: "Ethiopia's iconic multi-spice blend — bold, warming, complex.",
    price: 480,
    category: categories[3],
    categoryId: "cat_4",
    tags: ["berbere", "ethiopian", "blend", "spicy"],
    images: [
      { id: "img_14a", url: "https://images.unsplash.com/photo-1583394293214-5c3b93e673ac?w=800&q=80", alt: "Berbere Spice Blend" },
    ],
    stock: 75,
    unit: "100g",
    origin: "Ethiopia",
    rating: 4.8,
    reviewCount: 88,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-01-30",
  },
  {
    id: "prod_15",
    name: "Ras El Hanout",
    slug: "ras-el-hanout",
    description:
      "The crown jewel of Moroccan spice blending — 'top of the shop' in Arabic. Our blend includes over 25 premium spices, including dried rose petals, saffron, grains of paradise, cubeb pepper, and more.",
    shortDescription: "Moroccan luxury blend — over 25 premium spice ingredients.",
    price: 650,
    compareAtPrice: 800,
    category: categories[3],
    categoryId: "cat_4",
    tags: ["ras el hanout", "moroccan", "luxury", "blend"],
    images: [
      { id: "img_15a", url: "https://images.unsplash.com/photo-1638429347878-1fb51e1dbb43?w=800&q=80", alt: "Ras El Hanout" },
    ],
    stock: 60,
    unit: "75g",
    origin: "Morocco",
    rating: 4.9,
    reviewCount: 73,
    isFeatured: true,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-20",
  },
  // Additives
  {
    id: "prod_16",
    name: "Food-Grade Rose Water",
    slug: "food-grade-rose-water",
    description:
      "Pure, double-distilled rose water from Bulgarian Damask roses. Delicate floral aroma and flavour used in Middle Eastern desserts, lassis, rice dishes, and cocktails. No additives, 100% natural.",
    shortDescription: "Pure Bulgarian Damask rose water — 100% natural, double-distilled.",
    price: 340,
    category: categories[4],
    categoryId: "cat_5",
    tags: ["rose water", "desserts", "floral", "natural"],
    images: [
      { id: "img_16a", url: "https://images.unsplash.com/photo-1559235038-1ef7038e12c7?w=800&q=80", alt: "Rose Water" },
    ],
    stock: 95,
    unit: "200ml",
    origin: "Bulgaria",
    rating: 4.6,
    reviewCount: 39,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-01",
  },
  {
    id: "prod_17",
    name: "Saffron Threads",
    slug: "saffron-threads",
    description:
      "The world's most precious spice. Our Grade 1 saffron from Iran's Khorasan Province is hand-harvested, with deep red stigmas and maximum crocin content. Brings golden colour and honeyed, floral depth to rice, paella, biryani, and desserts.",
    shortDescription: "Grade 1 Khorasan saffron — world's most precious spice.",
    price: 2800,
    compareAtPrice: 3500,
    category: categories[4],
    categoryId: "cat_5",
    tags: ["saffron", "luxury", "golden", "premium"],
    images: [
      { id: "img_17a", url: "https://images.unsplash.com/photo-1567198179230-8bf05b060f08?w=800&q=80", alt: "Saffron Threads" },
    ],
    stock: 30,
    unit: "1g",
    origin: "Iran",
    rating: 5.0,
    reviewCount: 47,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-01",
  },
  {
    id: "prod_18",
    name: "Vanilla Beans (Grade A)",
    slug: "vanilla-beans-grade-a",
    description:
      "Plump, oil-rich Grade A Bourbon vanilla beans from Madagascar. Each bean is loaded with thousands of vanilla caviar seeds. Perfect for custards, ice cream, cakes, and any recipe where real vanilla flavour matters.",
    shortDescription: "Plump Madagascar Bourbon Grade A vanilla beans.",
    price: 1200,
    compareAtPrice: 1500,
    category: categories[4],
    categoryId: "cat_5",
    tags: ["vanilla", "baking", "desserts", "premium"],
    images: [
      { id: "img_18a", url: "https://images.unsplash.com/photo-1559235038-1ef7038e12c7?w=800&q=80", alt: "Vanilla Beans" },
    ],
    stock: 55,
    unit: "2 pods",
    origin: "Madagascar",
    rating: 4.9,
    reviewCount: 82,
    isFeatured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: "2025-01-18",
  },
  // Specialty Salts
  {
    id: "prod_19",
    name: "Himalayan Pink Salt (Fine)",
    slug: "himalayan-pink-salt-fine",
    description:
      "Ancient mineral-rich salt from the Khewra Salt Mine in Pakistan. 84 trace minerals give it a subtle, complex flavour and beautiful rose-pink colour. Finely ground for everyday cooking, seasoning, and baking.",
    shortDescription: "84-mineral ancient pink salt, finely ground.",
    price: 280,
    category: categories[5],
    categoryId: "cat_6",
    tags: ["pink salt", "himalayan", "mineral", "cooking"],
    images: [
      { id: "img_19a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Himalayan Pink Salt" },
    ],
    stock: 220,
    unit: "500g",
    origin: "Pakistan",
    rating: 4.5,
    reviewCount: 110,
    isFeatured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: "2025-02-01",
  },
  {
    id: "prod_20",
    name: "Smoked Sea Salt",
    slug: "smoked-sea-salt",
    description:
      "Hand-harvested Atlantic sea salt cold-smoked over oak and cherry wood for 48 hours. Adds incredible depth and smoky complexity to finished dishes, grilled meats, salads, and even chocolate desserts.",
    shortDescription: "Oak & cherry cold-smoked Atlantic sea salt — 48-hour process.",
    price: 420,
    category: categories[5],
    categoryId: "cat_6",
    tags: ["smoked salt", "bbq", "finishing", "oak"],
    images: [
      { id: "img_20a", url: "https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=800&q=80", alt: "Smoked Sea Salt" },
    ],
    stock: 85,
    unit: "200g",
    origin: "Portugal",
    rating: 4.7,
    reviewCount: 54,
    isFeatured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: "2025-03-08",
  },
];

// ─── Reviews ──────────────────────────────────────────────────────────────────

export const reviews: Review[] = [
  {
    id: "rev_1",
    productId: "prod_1",
    author: "Amina Ochieng",
    rating: 5,
    title: "Absolutely incredible quality",
    body: "I've been buying cinnamon for years and this is hands-down the best I've ever had. The aroma fills the whole kitchen when you open the bag. Will never buy supermarket cinnamon again!",
    createdAt: "2025-02-15",
    verified: true,
  },
  {
    id: "rev_2",
    productId: "prod_1",
    author: "James Kariuki",
    rating: 5,
    title: "A game changer for my chai",
    body: "My morning chai has never been better. Real Ceylon cinnamon has such a different flavour from the cassia you get in shops. Totally worth it.",
    createdAt: "2025-03-01",
    verified: true,
  },
  {
    id: "rev_3",
    productId: "prod_7",
    author: "Fatuma Hassan",
    rating: 5,
    title: "Vibrant colour, deep flavour",
    body: "The colour of this turmeric is stunning — a deep, saturated gold. It made my curries look like restaurant food. Fast delivery too!",
    createdAt: "2025-02-28",
    verified: true,
  },
  {
    id: "rev_4",
    productId: "prod_13",
    author: "David Mwangi",
    rating: 5,
    title: "Freshest garam masala I've ever tasted",
    body: "You can genuinely tell this was freshly ground. The fragrance is incredible and it transforms every dish. I ordered 3 packs this time.",
    createdAt: "2025-03-05",
    verified: true,
  },
  {
    id: "rev_5",
    productId: "prod_17",
    author: "Layla Al-Amin",
    rating: 5,
    title: "Genuine Grade 1 — worth every shilling",
    body: "I was hesitant given the price but this is real saffron. A tiny pinch makes the most beautifully golden, fragrant rice. Superb quality.",
    createdAt: "2025-03-10",
    verified: true,
  },
  {
    id: "rev_6",
    productId: "prod_2",
    author: "Grace Wanjiku",
    rating: 5,
    title: "The best pepper mill fill",
    body: "These Tellicherry peppercorns are large, aromatic and have incredible flavour. My whole family has noticed how much better the food tastes!",
    createdAt: "2025-02-20",
    verified: true,
  },
];

// ─── Users ───────────────────────────────────────────────────────────────────

export const users: User[] = [
  {
    id: "user_1",
    name: "Amina Ochieng",
    email: "amina@example.com",
    phone: "+254 712 345 678",
    role: "customer",
    createdAt: "2024-11-01",
    orderCount: 5,
    totalSpent: 12450,
  },
  {
    id: "user_2",
    name: "James Kariuki",
    email: "james@example.com",
    phone: "+254 721 234 567",
    role: "customer",
    createdAt: "2024-12-03",
    orderCount: 2,
    totalSpent: 3800,
  },
  {
    id: "user_3",
    name: "Fatuma Hassan",
    email: "fatuma@example.com",
    phone: "+254 733 456 789",
    role: "customer",
    createdAt: "2025-01-15",
    orderCount: 3,
    totalSpent: 6700,
  },
  {
    id: "user_4",
    name: "Admin User",
    email: "admin@glowspice.co.ke",
    role: "admin",
    createdAt: "2024-10-01",
  },
  {
    id: "user_5",
    name: "Grace Wanjiku",
    email: "grace@example.com",
    phone: "+254 742 567 890",
    role: "customer",
    createdAt: "2025-01-22",
    orderCount: 1,
    totalSpent: 1850,
  },
  {
    id: "user_6",
    name: "David Mwangi",
    email: "david@example.com",
    phone: "+254 751 678 901",
    role: "customer",
    createdAt: "2025-02-08",
    orderCount: 4,
    totalSpent: 9250,
  },
];

// ─── Orders ──────────────────────────────────────────────────────────────────

export const orders: Order[] = [
  {
    id: "ord_1",
    orderNumber: "GS-2025-0001",
    customerId: "user_1",
    customer: users[0],
    items: [
      { product: products[0], quantity: 2, unitPrice: 450, subtotal: 900 },
      { product: products[6], quantity: 1, unitPrice: 220, subtotal: 220 },
    ],
    status: "delivered",
    shippingAddress: {
      fullName: "Amina Ochieng",
      email: "amina@example.com",
      phone: "+254 712 345 678",
      address: "14 Garden Estate Road",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00100",
      country: "Kenya",
    },
    subtotal: 1120,
    shippingCost: 200,
    tax: 180,
    total: 1500,
    paymentMethod: "M-Pesa",
    createdAt: "2025-02-10",
    updatedAt: "2025-02-14",
  },
  {
    id: "ord_2",
    orderNumber: "GS-2025-0002",
    customerId: "user_2",
    customer: users[1],
    items: [
      { product: products[12], quantity: 1, unitPrice: 420, subtotal: 420 },
      { product: products[14], quantity: 1, unitPrice: 650, subtotal: 650 },
    ],
    status: "shipped",
    shippingAddress: {
      fullName: "James Kariuki",
      email: "james@example.com",
      phone: "+254 721 234 567",
      address: "Westlands Business Park, Suite 4B",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00800",
      country: "Kenya",
    },
    subtotal: 1070,
    shippingCost: 200,
    tax: 171,
    total: 1441,
    paymentMethod: "Card",
    createdAt: "2025-03-01",
    updatedAt: "2025-03-03",
  },
  {
    id: "ord_3",
    orderNumber: "GS-2025-0003",
    customerId: "user_3",
    customer: users[2],
    items: [
      { product: products[16], quantity: 1, unitPrice: 2800, subtotal: 2800 },
    ],
    status: "processing",
    shippingAddress: {
      fullName: "Fatuma Hassan",
      email: "fatuma@example.com",
      phone: "+254 733 456 789",
      address: "Mombasa Road, Mlolongo",
      city: "Machakos",
      county: "Machakos",
      postalCode: "90100",
      country: "Kenya",
    },
    subtotal: 2800,
    shippingCost: 300,
    tax: 448,
    total: 3548,
    paymentMethod: "M-Pesa",
    createdAt: "2025-03-08",
    updatedAt: "2025-03-08",
  },
  {
    id: "ord_4",
    orderNumber: "GS-2025-0004",
    customerId: "user_5",
    customer: users[4],
    items: [
      { product: products[1], quantity: 2, unitPrice: 380, subtotal: 760 },
      { product: products[9], quantity: 1, unitPrice: 210, subtotal: 210 },
      { product: products[10], quantity: 1, unitPrice: 280, subtotal: 280 },
    ],
    status: "pending",
    shippingAddress: {
      fullName: "Grace Wanjiku",
      email: "grace@example.com",
      phone: "+254 742 567 890",
      address: "Karen, Bogani East Rd",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00502",
      country: "Kenya",
    },
    subtotal: 1250,
    shippingCost: 200,
    tax: 200,
    total: 1650,
    paymentMethod: "Card",
    createdAt: "2025-03-12",
    updatedAt: "2025-03-12",
  },
  {
    id: "ord_5",
    orderNumber: "GS-2025-0005",
    customerId: "user_6",
    customer: users[5],
    items: [
      { product: products[3], quantity: 3, unitPrice: 320, subtotal: 960 },
      { product: products[4], quantity: 2, unitPrice: 180, subtotal: 360 },
      { product: products[13], quantity: 1, unitPrice: 480, subtotal: 480 },
    ],
    status: "confirmed",
    shippingAddress: {
      fullName: "David Mwangi",
      email: "david@example.com",
      phone: "+254 751 678 901",
      address: "Kilimani, Argwings Kodhek Rd",
      city: "Nairobi",
      county: "Nairobi",
      postalCode: "00200",
      country: "Kenya",
    },
    subtotal: 1800,
    shippingCost: 200,
    tax: 288,
    total: 2288,
    paymentMethod: "M-Pesa",
    createdAt: "2025-03-13",
    updatedAt: "2025-03-13",
  },
];

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

export const dashboardStats: DashboardStats = {
  totalRevenue: 483250,
  totalOrders: 147,
  totalCustomers: 89,
  totalProducts: products.length,
  revenueChange: 18.4,
  ordersChange: 12.2,
  customersChange: 24.7,
  recentOrders: orders,
};

// ─── Helpers ─────────────────────────────────────────────────────────────────

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(categoryId: string): Product[] {
  return products.filter((p) => p.categoryId === categoryId);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.isFeatured);
}

export function getBestSellers(): Product[] {
  return products.filter((p) => p.isBestSeller);
}

export function getNewArrivals(): Product[] {
  return products.filter((p) => p.isNew);
}

export function getProductReviews(productId: string): Review[] {
  return reviews.filter((r) => r.productId === productId);
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((c) => c.slug === slug);
}

export function getOrderById(id: string): Order | undefined {
  return orders.find((o) => o.id === id);
}

export function searchProducts(query: string): Product[] {
  const q = query.toLowerCase();
  return products.filter(
    (p) =>
      p.name.toLowerCase().includes(q) ||
      p.description.toLowerCase().includes(q) ||
      p.tags.some((t) => t.includes(q))
  );
}
